import React, { useState } from "react";
import lineAnimation from "../../lottie/left_lines.json";
import Lottie from "lottie-react";

// ACE Digital Solutions FAQ Content
const faqs = [
  {
    question: "What is an AI Clone Avatar and how does it work?",
    answer:
      "An AI Clone Avatar is a hyper-realistic digital replica of yourself. We use advanced machine learning to capture your voice, facial expressions, and mannerisms. Once created, your avatar can generate high-quality video content 24/7 simply from text scripts, saving you countless hours of filming.",
  },
  {
    question: "How long does it take to create a CGI advertisement?",
    answer:
      "The timeline for CGI (Computer-Generated Imagery) advertising depends on the complexity of the project. Typically, a high-end 15 to 30-second CGI product ad takes about 2 to 4 weeks from initial storyboarding to final render and delivery.",
  },
  {
    question: "Do you offer custom pricing for specific projects?",
    answer:
      "Yes, absolutely. While we have structured packages for standard services like video editing and social media management, our AI Avatar and CGI projects are highly customized. We provide custom quotes based on your specific brand requirements and goals.",
  },
  {
    question: "Can I use my AI Avatar for multiple platforms?",
    answer:
      "Yes! The video content generated by your AI Avatar can be formatted and optimized for any platform, including YouTube, Instagram Reels, TikTok, Facebook Ads, and even internal corporate training videos.",
  },
  {
    question: "What is required from me to build an AI Clone?",
    answer:
      "To create your custom AI Avatar, we will need a 2 to 5-minute high-quality video recording of you speaking directly to the camera in a well-lit environment. We provide a step-by-step recording guide to make the process as easy as possible for you.",
  },
];

export default function FaqOne() {
  const [activeFAQ, setActiveFAQ] = useState(0);

  const toggleFAQ = (index) => {
    setActiveFAQ(activeFAQ === index ? null : index);
  };

  return (
    <section className="relative pt-[80px] md:pt-[130px]" id="faq">
      <div className="w-full pb-16 md:pb-[130px] relative z-10">
        <div className="mx-auto theme-container">
          {/* Main Wrapper Border changed to Brand Blue tint */}
          <div className="relative flex items-center justify-center px-4 py-10 overflow-hidden border md:px-0 md:py-20 rounded-3xl border-[#094a66]/20 bg-main-gray">
            
            {/* Animated Circles - Colors changed to Brand Green tint */}
            <div className="absolute flex items-center justify-center w-2 h-2 -bottom-1 -right-1">
              <div className="animated_circle bg-[#6db305]/10"></div>
              <div className="animated_circle2 bg-[#6db305]/10"></div>
              <div className="animated_circle3 bg-[#6db305]/10"></div>
              <div className="animated_circle4 bg-[#6db305]/10"></div>
            </div>

            <div className="max-w-[850px] w-full flex justify-center items-center flex-col relative z-10">
              {/* FIXED: Section Tag with requested Brand Green and Important flag */}
              <h1 className="py-1.5 px-5 mb-4 text-xs font-semibold !text-[#6db305] !bg-[#6db305]/10 !border !border-[#6db305]/20 rounded-full uppercase tracking-widest shadow-[0_0_10px_rgba(109,179,5,0.1)]">
                FAQs
              </h1>
              <h2 className="mt-5 font-bold text-24 sm:text-48 text-main-black font-montserrat text-center">
                Frequently Asked Questions
              </h2>
              
              <div className="flex flex-col gap-3 w-full mt-8 md:mt-12 p-0 sm:p-5">
                {faqs.map((faq, index) => (
                  <div
                    key={index}
                    // Hover and Active states changed to Brand Green with Glow
                    className={`py-4 md:py-5 px-5 md:px-9 w-full bg-white rounded-2xl overflow-hidden transition-all duration-300 cursor-pointer border border-slate-100 hover:border-[#6db305]/40 ${
                      activeFAQ === index ? "shadow-[0_0_20px_rgba(109,179,5,0.12)] border-[#6db305]/30" : "shadow-sm"
                    }`}
                    onClick={() => toggleFAQ(index)}
                  >
                    <div className="flex items-center justify-between w-full h-fit">
                      {/* Active Text color changed to Brand Blue */}
                      <h1 className={`font-bold sm:text-lg transition-colors duration-300 pr-4 ${activeFAQ === index ? "text-[#094a66]" : "text-main-black"}`}>
                        {faq.question}
                      </h1>
                      <div className="flex-shrink-0 ml-4">
                        <svg
                          // Arrow icon colors changed to Brand Green
                          className={`w-4 h-4 transition-transform duration-300 ${activeFAQ === index ? "rotate-180 text-[#6db305]" : "text-main-black"}`}
                          viewBox="0 0 19 10"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M2 2L9.5 8L17 2"
                            stroke="currentColor"
                            strokeWidth="3"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          />
                        </svg>
                      </div>
                    </div>
                    
                    {/* FAQ Answer Area */}
                    <div className={`transition-all duration-500 ease-in-out overflow-hidden ${activeFAQ === index ? "max-h-96 opacity-100 mt-4" : "max-h-0 opacity-0 mt-0"}`}>
                      <p className="text-paragraph text-base leading-relaxed pr-4">
                        {faq.answer}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Lottie Animations Background */}
      <div className="absolute flex justify-between top-40 w-full pointer-events-none opacity-30 z-0">
        <Lottie animationData={lineAnimation} loop={true} className="w-[300px]" />
        <Lottie
          animationData={lineAnimation}
          className="transform rotate-180 w-[300px]"
          loop={true}
        />
      </div>
    </section>
  );
}